# Generated by Django 5.2.7 on 2025-10-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recursos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recursos',
            new_name='Recurso',
        ),
        migrations.AlterModelTable(
            name='recurso',
            table='core_recursos',
        ),
    ]
